export const appModal = {
	REGISTER: "REGISTER",
	ACCOUNT_DELETE_CONFIRM: "DELETE_ACCOUNT_CONFIRM",
	ACCOUNT_MANAGE: "MANAGE_ACCOUNT",
	SESSION_EXPIRED: "SESSION_EXPIRED",
	SESSION_EXPIRE_WARNING: "SESSION_EXPIRE_WARNING",
	SONG_DELETE_CONFIRM: "SONG_DELETE_CONFIRM",
	SONG_SET_DELETE_CONFIRM: "SONG_SET_DELETE_CONFIRM",
	CONFIRM: "CONFIRM",
} as const;
